import { systemUi } from "../fonts/config";
import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/navbar/navbar";
import Footer from "../components/footer/footer";
import { Providers } from "./providers"; 

export const metadata: Metadata = {
  title: "Gstore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth" lang="en">
      <body className={`${systemUi.className} antialiased`}>
        {/* Wrap content with Redux Provider */}
        <Providers>
          <div className="min-h-screen flex flex-col mx-auto">
            <Header />
            
            <main className="flex-1 container mx-auto px-2 py-4">
              {children}
            </main>

            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}